--NUMBER OF CUSTOMERS BY COUNTRY
SELECT Country,COUNT(CustomerID) AS [NUMBER OF CUSTOMERS],
FORMAT(CAST(COUNT(CustomerID) AS FLOAT)/(SELECT COUNT(CustomerID) FROM Customers),'P2') [PERCENTAGE]
FROM Customers
GROUP BY Country
ORDER BY [NUMBER OF CUSTOMERS] DESC;


--CUSTOMERS WITH THE MOST SALES SHARE
SELECT CustomerID,FORMAT(SUM(ProductID*UnitPrice*(1-Discount)),'C2') AS [SALES AMOUNT],
FORMAT(SUM(ProductID*UnitPrice*(1-Discount))/(SELECT SUM(ProductID*UnitPrice*(1-Discount)) FROM ORDERS O JOIN [Order Details] OD ON O.OrderID=OD.OrderID),'P2') AS [PERCENTAGE]
FROM Orders O
JOIN [Order Details] OD ON O.OrderID=OD.OrderID
GROUP BY CustomerID 
ORDER BY SUM(ProductID*UnitPrice*(1-Discount)) DESC;

-- WHICH EMPLOYEES CONTRIBUTE TO MOST SALES
WITH T1 AS
(
SELECT EmployeeID,
COUNT(DISTINCT O.OrderID) AS [NUMBER OF ORDERS PLACED],
SUM(Quantity*UnitPrice*(1-Discount)) AS [SALES UNFORMATED],
FORMAT(SUM(Quantity*UnitPrice*(1-Discount)),'C2') AS [SALES AMOUNT],
FORMAT(SUM(Quantity*UnitPrice*(1-Discount))/(SELECT SUM(Quantity*UnitPrice*(1-Discount)) FROM ORDERS O JOIN [Order Details] OD ON O.OrderID=OD.OrderID),'P2') AS [SALES PERCENTAGE] 
FROM Orders O
JOIN [Order Details] OD ON O.OrderID=OD.OrderID
GROUP BY EmployeeID
)
SELECT T1.EmployeeID, CONCAT(FirstName,' ',LastName) AS [EMPLOYEE], [NUMBER OF ORDERS PLACED],[SALES AMOUNT],[SALES PERCENTAGE]
FROM T1
JOIN Employees E ON T1.EmployeeID=E.EmployeeID
ORDER BY [SALES UNFORMATED] DESC;


--SALES BY PERIOD
WITH T1 AS
(
SELECT FORMAT(OrderDate,'MM-yyyy') AS [PERIOD], SUM(Quantity*UnitPrice*(1-Discount)) AS SALES
FROM Orders O
JOIN [Order Details] OD ON O.OrderID=OD.OrderID
GROUP BY FORMAT(OrderDate,'MM-yyyy')
)
SELECT [PERIOD],SALES,LAG(SALES,1) OVER(ORDER BY [PERIOD]) AS [PREVIOUS MONTH SALES],
FORMAT(SALES/(LAG(SALES,1) OVER(ORDER BY [PERIOD]))-1,'P2') AS [CHANGE VS PREVIOUS MONTH]
FROM T1;

-- WHICH ARE MOST DEMANDED PRODUCTS AND WHICH SUPPLIERS ARE THEY PROVIDED FROM
WITH T1 AS
(
SELECT ProductID, SUM(Quantity) AS [QUANTITY SOLD],SUM(Quantity*UnitPrice*(1-Discount)) AS [SALES AMOUNT]
FROM [Order Details]
GROUP BY ProductID
)
,T2 AS
(
SELECT P.*,T1.[QUANTITY SOLD],T1.[SALES AMOUNT]
FROM Products P
LEFT JOIN T1 ON P.ProductID=T1.ProductID
)
SELECT ProductID,SUM([QUANTITY SOLD]) AS [QUANTITY SOLD], FORMAT(SUM([SALES AMOUNT]),'C2') AS [SALES AMOUNT]
FROM T2
GROUP BY ProductID
ORDER BY SUM([SALES AMOUNT]) DESC;

--PRODUCTS THAT APPEAR IN MOST ORDERS
SELECT ProductID, 
COUNT(DISTINCT OrderID) AS [APPEARANCES], 
FORMAT(CAST(COUNT(DISTINCT OrderID) AS FLOAT)/(SELECT COUNT(DISTINCT OrderID) FROM [Order Details]),'P2') AS [PERCENTAGE]
FROM [Order Details] OD
GROUP BY ProductID
ORDER BY APPEARANCES DESC;

-- PRODUCTS MOST FREQUENTLY BOUGHT TOGETHER
WITH T1 AS
(
SELECT OD1.OrderID, OD1.ProductID AS PRODUCT_ID1,OD2.ProductID AS PRODUCT_ID2
FROM [Order Details] OD1
JOIN [Order Details] OD2 ON OD1.OrderID=OD2.OrderID
)
,T2 AS
(
SELECT PRODUCT_ID1,PRODUCT_ID2,COUNT(OrderID) AS [NUMBER OF ORDERS]
FROM T1
WHERE PRODUCT_ID1>PRODUCT_ID2
GROUP BY PRODUCT_ID1,PRODUCT_ID2
)
SELECT T2.*, P1.ProductName AS [FIRST PRODUCT], P2.ProductName AS [SECOND PRODUCT]
FROM T2
JOIN Products P1 ON T2.PRODUCT_ID1=P1.ProductID
JOIN Products P2 ON T2.PRODUCT_ID2=P2.ProductID
ORDER BY [NUMBER OF ORDERS] DESC;


-- AVERAGE SHIPPING DAYS BY COUNTRY AND SHIPPER. FIND THE FASTEST OPTION FOR EACH COUNTRY
WITH T1 AS
(
SELECT ShipCountry,ShipVia,AVG(DATEDIFF(DAY,OrderDate,ShippedDate)) AS [AVG SHIPPING DAYS]
FROM Orders O
GROUP BY ShipCountry,ShipVia
)
,T2 AS
(
SELECT ShipCountry,CompanyName AS [SHIPPER],[AVG SHIPPING DAYS], ROW_NUMBER() OVER(PARTITION BY SHIPCOUNTRY ORDER BY ShipCountry,[AVG SHIPPING DAYS]) AS [SHIPPER RANK]
FROM T1
JOIN Shippers SH ON T1.ShipVia=SH.ShipperID
)
SELECT T2.*
FROM
(SELECT ShipCountry, MIN([AVG SHIPPING DAYS]) AS [AVG SHIPPING DAYS]
FROM T2
GROUP BY ShipCountry) A
JOIN T2 ON A.ShipCountry=T2.ShipCountry AND A.[AVG SHIPPING DAYS]=T2.[AVG SHIPPING DAYS]
ORDER BY [AVG SHIPPING DAYS];